server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
spring.application.name=email-service
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=instamartapp
spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true
spring.datasource.tomcat.default-auto-commit=false

# JavaMailSender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=captainprice2905@gmail.com
spring.mail.password=lzyu egkk zepd niia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

